name: app
type: python:3.9
disk: 512

variables:
  env:
    FLASK_ENV: 'production'

web:
  commands:
    start: python app.py #--host 127.0.0.1 --port $PORT

hooks:
  build: |
    pip install -r requirements.txt
  deploy: |
    python app.py db upgrade
    
relationships:
  database: "mysqldatabase:mysql"
