name: app
type: python:3.9
disk: 512

variables:
  env:
    FLASK_APP: 'app.py'
    FLASK_ENV: 'production'

web:
  commands:
    start: python app.py #--host 127.0.0.1 --port $PORT

hooks:
  build: |
    pip install -r requirements.txt
  deploy: |
    /Users/b/Documents/shopp/Grocery-Tracker/venv/bin/flask db upgrade
    
relationships:
  database: "mysqldatabase:mysql"
