name: app
type: python:3.9
disk: 512


web:
  commands:
    start: python app.py #--host 127.0.0.1 --port $PORT

hooks:
  build: |
    pip install -r requirements.txt
    apt-get update
    apt-get install -y tesseract-ocr
  
variables:
    env:
        DATABASE_URL: 'postgresql://postgres:password@localhost:5432/postgres'

