"""Added account_id to Grocery

Revision ID: 7f6dfdb4433e
Revises: 6ab2c585fe28
Create Date: 2023-11-02 00:51:18.860048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6dfdb4433e'
down_revision = '6ab2c585fe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer()))
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
