"https://{default}/":
  type: upstream
  upstream: "app:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/ui":
  type: upstream
  upstream: "app:http"

"https://{default}/ui/":
  type: upstream
  upstream: "app:http"
