"https://{default}/":
  type: upstream
  upstream: "app:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/api/":
  type: upstream
  upstream: "app:http"

"https://{default}/api":
  type: upstream
  upstream: "app:http"
